name: Build binary

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-binary:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            requirements*.txt
      - run: python -m pip install -r requirements-dev.txt
      - name: 'Run PyInstaller'
        run: ./pyinstaller.bat
        env:
          PYTHONOPTIMIZE: 1
      - name: 'Release'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/remid_cookie_grabber.exe
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
